#!/usr/bin/env bash
#
# tests/api/smoke/dev_server.sh — interactive dev server for the
# php-tree-visualizer UI.
#
# Builds a fixture under a temp dir, writes a collector.toml with a
# fixed dev token, and starts `php -S` against the smoke router so
# the operator can browse the live UI from a real browser.
#
# Usage:
#   bash tests/api/smoke/dev_server.sh                 # bind 0.0.0.0:8080
#   bash tests/api/smoke/dev_server.sh 127.0.0.1:8080  # loopback only
#   bash tests/api/smoke/dev_server.sh 0.0.0.0:9000    # different port
#
# Defaults to 0.0.0.0:8080 so the page is reachable from another
# device on the same LAN (handy for testing on a phone). The token
# is printed at the top of the output along with the URL.
#
# Ctrl-C tears down `php -S` and removes the temp directory.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
cd "$REPO_ROOT"

BIND="${1:-0.0.0.0:8080}"
TOKEN="dev-token-xyz"
SALT="dev-salt-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

TMP="$(mktemp -d -t phptv-dev.XXXXXX)"
DATA_DIR="$TMP/data"
CONFIG_PATH="$TMP/collector.toml"
mkdir -p "$DATA_DIR/traces"

cleanup() {
    if [[ -n "${SERVER_PID:-}" ]] && kill -0 "$SERVER_PID" 2>/dev/null; then
        kill "$SERVER_PID" 2>/dev/null || true
    fi
    rm -rf "$TMP"
}
trap cleanup EXIT INT TERM

cat > "$CONFIG_PATH" <<EOF
# Auto-generated by tests/api/smoke/dev_server.sh — do not edit.
[server]
bind = "127.0.0.1:8088"
max_body_bytes = 67108864
queue_capacity = 256
tls = false

[auth]
token = "$TOKEN"
session_salt = "$SALT"

[storage]
data_dir = "$DATA_DIR"
retention_days = 30

[finalize]
idle_seconds = 30
tick_seconds = 5
EOF

# Build fixture data: three traces in the index, plus one per-trace
# file (for the second trace) so the Phase 4 trace-detail endpoints
# have something to return. The trace_key "222…" lines up with the
# row the operator is most likely to click.
php -r '
require "tests/api/fixtures/make_index_sqlite.php";
require "tests/api/fixtures/make_trace_sqlite.php";

$dataDir = $argv[1];

make_index_sqlite($dataDir . "/index.sqlite", [
    [
        "trace_key" => str_repeat("1", 32),
        "uri_or_script" => "/srv/app/index.php",
        "start_time_ns" => 1700000000000000000,
    ],
    [
        "trace_key" => str_repeat("2", 32),
        "uri_or_script" => "/srv/app/bin/run-tests.php",
        "start_time_ns" => 1700000001000000000,
        "anomaly_count" => 1,
        "dropped_records" => 42,
    ],
    [
        "trace_key" => str_repeat("3", 32),
        "uri_or_script" => "/srv/app/cron/run-nightly.php",
        "start_time_ns" => 1700000002000000000,
        "state" => "active",
    ],
]);

$key = str_repeat("2", 32);
make_trace_sqlite(
    $dataDir . "/traces/$key.sqlite",
    [
        "trace_key" => $key,
        "uri_or_script" => "/srv/app/bin/run-tests.php",
        "start_time_ns" => 1700000001000000000,
    ],
    [
        1 => ["fqn" => "main"],
        2 => ["fqn" => "PDO::query", "file" => "/srv/app/db.php", "line" => 47],
        3 => ["fqn" => "render_template", "file" => "/srv/app/views.php", "line" => 18],
    ],
    [
        ["node_id" => 2, "parent_node_id" => 1, "fn_id" => 1, "depth" => 1,
         "total_wall_ns" => 1_543_210_000, "call_count" => 1],
        ["node_id" => 3, "parent_node_id" => 2, "fn_id" => 2, "depth" => 2,
         "total_wall_ns" =>   900_000_000, "call_count" => 24],
        ["node_id" => 4, "parent_node_id" => 2, "fn_id" => 3, "depth" => 2,
         "total_wall_ns" =>   400_000_000, "call_count" => 12],
    ]
);
' "$DATA_DIR"

cat <<EOF

╭──────────────────────────────────────────────────────────────╮
│                                                              │
│   php-tree-visualizer — dev server                           │
│                                                              │
│   Bind:    http://$BIND
│   Login:   http://$BIND/viz/login.html
│                                                              │
│   Token to paste:    $TOKEN
│                                                              │
│   Three traces in the list; the second one ("run-tests.php") │
│   has a per-trace SQLite file so the detail page renders     │
│   a real call tree. Clicking that row lands on the           │
│   trace-detail view; the other two 404 (no per-trace file). │
│                                                              │
│   Press Ctrl-C to shut down + clean up the temp fixture.     │
│                                                              │
╰──────────────────────────────────────────────────────────────╯

EOF

# `wait` so a Ctrl-C delivers SIGINT to this shell and our trap runs
# cleanly (php -S without `&` would block, but we want our cleanup
# trap to fire whether the user hits Ctrl-C or kills the process).
PHPTV_CONFIG="$CONFIG_PATH" php \
    -S "$BIND" \
    tests/api/smoke/router.php &
SERVER_PID=$!

wait "$SERVER_PID"
