<?php

declare(strict_types=1);

/**
 * Write a temporary collector.toml in tmp and return its path.
 *
 *   make_config(array $opts = []): string
 *
 * Defaults to a self-consistent dev config with a fixed token and
 * salt. Pass overrides per section, e.g.:
 *
 *   make_config([
 *       'auth' => ['token' => 'unit-test-token-xyz'],
 *       'storage' => ['data_dir' => $tmpDataDir],
 *   ]);
 */

/**
 * @param array<string, array<string, scalar>> $overrides
 */
function make_config(array $overrides = []): string
{
    $defaults = [
        'server' => [
            'bind' => '127.0.0.1:8088',
            'max_body_bytes' => 67108864,
            'queue_capacity' => 256,
            'tls' => false,
        ],
        'auth' => [
            'token'        => 'unit-test-token-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
            'session_salt' => 'unit-test-salt-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
        ],
        'storage' => [
            'data_dir' => sys_get_temp_dir() . '/phptv-test-data',
            'retention_days' => 30,
        ],
        'finalize' => [
            'idle_seconds' => 30,
            'tick_seconds' => 5,
        ],
    ];

    $sections = array_replace_recursive($defaults, $overrides);

    $lines = ["# fixture collector.toml generated by tests"];
    foreach ($sections as $section => $kv) {
        $lines[] = "";
        $lines[] = "[{$section}]";
        foreach ($kv as $k => $v) {
            $lines[] = "{$k} = " . toml_format_value($v);
        }
    }
    $lines[] = "";

    $path = tempnam(sys_get_temp_dir(), 'phptv_conf_');
    if ($path === false) {
        throw new \RuntimeException('tempnam failed');
    }
    file_put_contents($path, implode("\n", $lines));
    return $path;
}

/**
 * Format a single TOML scalar. Strings get double quotes with bare
 * backslash escaping; booleans and ints are emitted verbatim.
 */
function toml_format_value(mixed $v): string
{
    if (is_bool($v)) {
        return $v ? 'true' : 'false';
    }
    if (is_int($v)) {
        return (string) $v;
    }
    if (is_string($v)) {
        $escaped = strtr($v, [
            "\\" => "\\\\",
            "\"" => "\\\"",
            "\n" => "\\n",
        ]);
        return '"' . $escaped . '"';
    }
    throw new \InvalidArgumentException('unsupported TOML scalar type');
}
